-- SELECT SQL FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TARJETA';
CREATE SEQUENCE TARJETA_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 NOMINVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE USUARIO_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 NOMINVALUE NOCYCLE NOCACHE;

CREATE TABLE USUARIO(
    ID_USUARIO BIGINT NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    USUARIO VARCHAR(255) NOT NULL
);

ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY ( ID_USUARIO );

CREATE TABLE CLIENTE(
    IDENTIFICACION VARCHAR(255) NOT NULL,
    TIPO_IDENTIFICACION VARCHAR(255) NOT NULL,
    DIRECCION VARCHAR(255),
    NOMBRE VARCHAR(255) NOT NULL,
    TELEFONO BIGINT,
    FECHA_REGISTRO TIMESTAMP(6) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) NOT NULL
);

ALTER TABLE  CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY ( IDENTIFICACION ,TIPO_IDENTIFICACION);

CREATE TABLE TARJETA(
    ID_TARJETA BIGINT NOT NULL,
    CVV VARCHAR(255) NOT NULL,
    FECHA_VENCIMIENTO VARCHAR(255) NOT NULL,
    NUMERO_TARJETA VARCHAR(255) NOT NULL,
    TIPO VARCHAR(50) NOT NULL,
    TIPO_IDENTIFICACION VARCHAR(255) NOT NULL,
    IDENTIFICACION VARCHAR(255) NOT NULL,
    FECHA_REGISTRO TIMESTAMP(6) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) NOT NULL
);

ALTER TABLE TARJETA ADD CONSTRAINT PK_CORTE PRIMARY KEY ( ID_TARJETA );

ALTER TABLE  TARJETA
    ADD CONSTRAINT FK_CLIENTE_TARJETA FOREIGN KEY ( TIPO_IDENTIFICACION ,IDENTIFICACION )
        REFERENCES  CLIENTE ( TIPO_IDENTIFICACION ,IDENTIFICACION );
