server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
  datasource:  
    url: jdbc:h2:mem:TARJETAS
    username: sa
    password: 'password'  
    driverClassName: org.h2.Driver
    schema: classpath:/db/schema.sql
    data: classpath:/db/data.sql
  jpa:
    hibernate:
      ddl-auto: none #update #create-drop
    properties:
      hibernate:
        show_sql: true
      jdbc:
        batch_size: 1000
      order_inserts: true
      order_updates: true
    database-platform: org.hibernate.dialect.H2Dialect
application:
  autorizacion:
    url: http://localhost:${server.port}/api/autorizacion/validar